source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'
use_frameworks!

target 'iosBleSdkTestApp' do
  pod 'PolarBleSdk', :git => 'https://github.com/makevisible/polar-ble-sdk.git', :tag => '6.4.4-visible'
end
